# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    The version of the OpenAPI document: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts_staging
from xepmts_staging.api.xenonnt_nveto_gain_api import XenonntNvetoGainApi  # noqa: E501
from xepmts_staging.rest import ApiException


class TestXenonntNvetoGainApi(unittest.TestCase):
    """XenonntNvetoGainApi unit test stubs"""

    def setUp(self):
        self.api = xepmts_staging.api.xenonnt_nveto_gain_api.XenonntNvetoGainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_xenonnt_nveto_gains(self):
        """Test case for get_xenonnt_nveto_gains

        Retrieves one or more XenonntNvetoGains  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
