# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    The version of the OpenAPI document: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts_staging
from xepmts_staging.api.xenonnt_tpc_dark_count_rate_api import XenonntTpcDarkCountRateApi  # noqa: E501
from xepmts_staging.rest import ApiException


class TestXenonntTpcDarkCountRateApi(unittest.TestCase):
    """XenonntTpcDarkCountRateApi unit test stubs"""

    def setUp(self):
        self.api = xepmts_staging.api.xenonnt_tpc_dark_count_rate_api.XenonntTpcDarkCountRateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_xenonnt_tpc_dark_count_rates(self):
        """Test case for get_xenonnt_tpc_dark_count_rates

        Retrieves one or more XenonntTpcDarkCountRates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
