# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    The version of the OpenAPI document: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import xepmts_staging
from xepmts_staging.models.inline_response20068 import InlineResponse20068  # noqa: E501
from xepmts_staging.rest import ApiException

class TestInlineResponse20068(unittest.TestCase):
    """InlineResponse20068 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20068
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = xepmts_staging.models.inline_response20068.InlineResponse20068()  # noqa: E501
        if include_optional :
            return InlineResponse20068(
                items = [
                    xepmts_staging.models.xenon1t_tpc_voltage_map_name.Xenon1tTpcVoltageMapName(
                        name = '0', 
                        _id = '0', )
                    ]
            )
        else :
            return InlineResponse20068(
        )

    def testInlineResponse20068(self):
        """Test InlineResponse20068"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
